# Generated by Django 5.0 on 2024-01-09 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_alter_infouser_biography_alter_infouser_url_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publicate', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('legend', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('url_img', models.URLField()),
                ('tag_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_user.categorypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_interactions', models.ManyToManyField(blank=True, related_name='publications_interacted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
