# Generated by Django 5.0 on 2024-01-12 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('description', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('instagram_handle', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('event_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
